# Site settings
title: Help your comunity find the best doctors!
logo: Best Doctor
slogan: 

email:
description: > # this means to ignore newlines until "baseurl:"

# This URL is the main address for absolute links. Don't include a slash at the end.
#
url: "http://devuiux.github.io/bestdoctor" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

twitter_username:
github_username:

# Build settings
markdown: kramdown
